name: Deploy

on:
  push:
    branches: [main]
  pull_request:

jobs:
  deploy:
    if: github.repository_owner == 'withastro'
    permissions:
      contents: read
    uses: withastro/automation/.github/workflows/cloudflare-deploy.yml@fc0f1c3adade217eeaa4257defedb23bc5f4dd87 # v1.1.1
    with:
      preview-domain: previews.contribute.docs.astro.build
      artifact-paths: |
        dist/
        wrangler.jsonc
      install-command: pnpm install
      build-command: pnpm run build
      node-version: "24.14.1"
      package-manager: pnpm
    secrets:
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
